### ISSUE TITLE
Standard Browserify/Babel require does not work

### ISSUE THREAD

**Issue by AirmanEpic** [RobertMenke/JS-Polynomial-Regression#4]
Howdy! I take it development on this amazing piece of software has been halted but I wanted to bring this issue up. I struggled for several hours to get it to install for browser. I was 100% unable to get the import mechanic to work as listed. Instead, I had to go into the NPM package and edit every instance of imports or exports to require() and module.exports = (respectively). When I did this, I was able to use browserify in the standard way. 

I'm not sure exactly why the developer chose to use import like this instead of require, but it rendered the package unusable until I manually edited it. Just wanted you to know.

**Comment by RobertMenke** [comment]
Hey, thanks for the issue report. This was intended to be used with webpack and I'm not planning to support other tooling.
